# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'logging_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15logging_service.proto\x12\x07logging\"\x07\n\x05\x45mpty\"\'\n\nLogRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1c\n\x08Messages\x12\x10\n\x08messages\x18\x01 \x01(\t2q\n\x0eLoggingService\x12\x31\n\nLogMessage\x12\x13.logging.LogRequest\x1a\x0e.logging.Empty\x12,\n\x07GetLogs\x12\x0e.logging.Empty\x1a\x11.logging.Messagesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_LOGREQUEST']._serialized_start=43
  _globals['_LOGREQUEST']._serialized_end=82
  _globals['_MESSAGES']._serialized_start=84
  _globals['_MESSAGES']._serialized_end=112
  _globals['_LOGGINGSERVICE']._serialized_start=114
  _globals['_LOGGINGSERVICE']._serialized_end=227
# @@protoc_insertion_point(module_scope)
